#!/bin/bash

BASE_PATH=`dirname $0`
JAVA_HOME="$JAVA_HOME"
KLASSPATH="$CLASSPATH:$BASE_PATH/lib/*:$BASE_PATH/classes"

"$JAVA_HOME/bin/java" \
-classpath "$KLASSPATH" \
app.hongs.cmdlet.CmdletRunner $@ \
--basepath "$BASE_PATH"